### ISSUE TITLE
use .env files

### ISSUE THREAD

**Issue by pharrisee** [attache/attache#5]
using something like github.com/joho/godotenv with it's autoload mechanism makes development (and production) much simpler.

I did sort of implement this (as a templated file) but was a little wary of breaking things since you use go-bindata and I'm not too familiar with it's usage.

**Comment by mccolljr** [comment]
If you want to open a PR, we can work through the implementation together. I have a file, `./build_cli.bash`, at the project root should take care of all of the `go-bindata`-related stuff for you.

I've been thinking about the best way to autoload configuration without being opinionated. This approach lines up with what I already have nicely, so as long as we can get the implementation looking good I'm all for including it.

**Comment by mccolljr** [comment]
Project card: https://github.com/attache/attache/projects/1#card-13701297

**Comment by mccolljr** [comment]
Started work on this in branch [environment_load](https://github.com/attache/attache/tree/environment_load)

Happy to accept further modifications before making the PR

**Comment by mccolljr** [comment]
merged #9
