### ISSUE TITLE
make port configurable

### ISSUE THREAD

**Issue by pharrisee** [attache/attache#6]
At the moment the port is hardcoded to 8080 (at least as far as I can see).  Using an env file (see #5) would allow almost any configuration to be done, e.g.:

```
DB_DRIVER=sqlite3
DB_DSN=:memory:
SESSION_SECRET=tis the session to be jolly
PORT=9999
```

Doing it this way doesn't preclude using the run.sh file as well and/or setting the env vars in a normal way.

**Comment by mccolljr** [comment]
The default `Run` method defaults to port 8080, but [`RunAt`](https://github.com/attache/attache/blob/master/application.go#L172) takes an argument in the same form as `http.ListenAndServe`, and [`RunWithServer`](https://github.com/attache/attache/blob/master/application.go#L181) lets you specify a custom `*http.Server` for even greater configuration.

**Comment by mccolljr** [comment]
I'm going to close this issue since there are a couple ways to do this already.

**Comment by pharrisee** [comment]
ah, ok, I wasn't looking at the code closely enough.
